// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "landing": {
    "titleLine1": "Right time.",
    "titleLine2": "Right ",
    "titleLine3": "place.",
    "description": "Meet people in the same bar, club, or event — we’ll handle the hello.",
    "joinTheWaitList": "Get early access",
    "joinTitle": "Launch night in Barcelona is coming",
    "joinSubtitle": "Join the waitlist for early access and the special launch nights.",
    "emailPlaceholder": "Enter your email",
    "joinButton": "Get early access",
    "joining": "Joining...",
    "joinSuccess": "You're in! Check your email.",
    "joinError": "Something went wrong. Please try again.",
    "featureTitle": "Experience dating differently",
    "featureDescription": "Discover a new way to connect with people that feels authentic and meaningful. Our platform is designed to help you build genuine connections.",
    "featureImageAlt": "Feature image"
  },
  "howItWorks": {
    "title": "How it works",
    "step1Title": "Open Meltt",
    "step1Description": "You’re at a bar, festival, club. You open the app and see who else is here.",
    "step2Title": "Make your move",
    "step2Description": "Someone catches your eye. You ping them — if they ping back, it’s a match.",
    "step3Title": "Meet for real",
    "step3Description": "Once you connect, take it offline. You chat, grab a drink, maybe more — the kind that doesn’t start with a swipe."
  },
  "facts": {
    "fact1": "✔️ No staring contests across the bar",
    "fact2": "✔️ No guessing games",
    "fact3": "✔️ Just real people, connecting"
  },
  "metadata": {
    "title": "Mellt | Right place. Right time.",
    "description": "Right place. Right time."
  }
};
export default messages;