// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "landing": {
    "title": "Emms Landing Page",
    "description": "Something is coming...",
    "joinTheWaitList": "Join wait list",
    "notInterested": "Not interested"
  },
  "logo": {
    "alt": "Next.js logo"
  },
  "vercel": {
    "logoAlt": "Vercel logomark"
  }
};
export default messages;